# Generated by Django 3.2 on 2021-04-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumbdash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='zip_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='users',
            name='zip_code',
            field=models.CharField(max_length=5),
        ),
    ]
