# Generated by Django 3.2 on 2021-04-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumbdash', '0002_auto_20210424_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='payment_last_four',
        ),
        migrations.AddField(
            model_name='users',
            name='venmo',
            field=models.CharField(default='lol', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
