# Generated by Django 3.2 on 2021-04-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumbdash', '0005_rename_address_restaurants_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='address',
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
