# Generated by Django 3.2 on 2021-04-25 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dumbdash', '0006_auto_20210424_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='instructions',
        ),
    ]
